opt_in_rules:
- force_unwrapping
- syntactic_sugar
- control_statement
- colon
- file_length
- leading_whitespace
- trailing_newline
- opening_brace
- comma
- force_cast
- variable_name_min_length
- trailing_semicolon
- function_body_length
- conditional_binding_cascade
- variable_name_max_length
- operator_whitespace
- legacy_constant
- return_arrow_whitespace
- closing_brace
- statement_position
- type_body_length
- legacy_constructor
- vertical_whitespace
- mark
- cyclomatic_complexity
- redundant_string_enum_value
- empty_parentheses_with_trailing_closure
- closure_parameter_position
- unused_closure_parameter
- implicit_getter
- weak_delegate
- void_return
- trailing_comma
- large_tuple
- shorthand_operator

disabled_rules:
- todo
- missing_docs
- valid_docs
- type_name
- variable_name
- cyclomatic_complexity
- function_body_length
- type_body_length
- file_length
- nesting
- weak_delegate
- trailing_whitespace

excluded:
- Pods
- Configurations

force_cast: warning #implicitly
force_try: warning #implicitly
empty_count: warning
line_length:
- 400 #warning
- 1000 #error
type_body_length:
- 350 #warning
function_body_length:
- 100 #warning
file_length:
- 400 #warning
cyclomatic_complexity:
- 10 #warning
function_parameter_count:
- 6 #warning